version: "3.7"

services:
  "jvtc-sw":
    build: .
    image: "ccr.ccs.tencentyun.com/jiu-docker/jvtc-sw"
    restart: always
    ports:
      - "3214:3214"
    networks:
      - bucai-network

networks:
  bucai-network:
    external: true