version: "3.7"

services:
  "jvtc-sw":
    build: .
    image: "registry.cn-hangzhou.aliyuncs.com/notbucai/jvtc-sw"
    restart: always
    ports: 
      - "3214:3214"
    networks:
      - bucai-network

networks:
  bucai-network:
    external: true